#console:
#    production_json:
#        CONSOLE_API:
#            ENDPOINT: https://console.api.example.com       # Change the endpoint
#        CONSOLE_API_V2:
#            ENDPOINT: https://console-v2.api.example.com    # Change the endpoint

global:
#    shared_conf:
#        TOKEN: '{TOKEN}'                                    # Change the system token

        DATABASES:
          default:
            host: mongodb+srv://mongodb.example.com         # Change the endpoint
            username: admin                                 # Change db username
            password: password                              # Change db password

mongodb:
  enabled: false