#console:
#    production_json:
#        CONSOLE_API:
#            ENDPOINT: https://console.api.example.com       # Change the endpoint
#        CONSOLE_API_V2:
#            ENDPOINT: https://console-v2.api.example.com    # Change the endpoint
#
#global:
#    shared_conf:
#        TOKEN: '{TOKEN}'                                    # Change the system token

supervisor:
    enabled: true
    application_scheduler:
        HOSTNAME: spaceone.svc.cluster.local    # Change the hostname
        CONNECTORS:
            KubernetesConnector:
                namespace: spaceone             # Change the namespace